TestInterIntefacemake: TestInterInterface.cpp InterInterface.cpp InterInterface.h
	g++ -std=c++11 -o TestInterIntefacemake TestInterInteface.cpp TestInterInterface.cpp -I/usr/local/include  -L/usr/local/lib  -lwiringPi  -lpthread
